Enable Good Job cron in production
nhsuk/manage-childrens-vaccinations pull request #1045
Opened 2024-02-23 15:18 UTC by misaka

This job will send out consent request emails to parents on the configured day for each session.

2024-02-23 16:21 UTC, tvararu requested changes

2024-02-23 16:21 UTC, tvararu commented on config/initializers/good_job.rb
> +  Settings.support_username.present? && Settings.support_password.present?
Support user creds are currently set via `manifest.yml` and are hard-coded in git for prod. Can we move them to `SECRETS` instead? That should be done as a separate PR/deploy to first roll it out in every env, followed by this PR to add the `/good-job` dashboard.

2024-02-24 16:08 UTC, tvararu approved these changes
👍 creds now moved to secrets so this can go in after we check that all is good with the other release

2024-02-24 22:25 UTC, misaka commented
This was manually deployed to test and it is working as expected.

2024-02-24 22:25 UTC, merged